# NEED TO INSTALL
# sudo pacman -S git helix yazi lazygit kitty fish fd ripgrep ffmpeg p7zip jq poppler rust-analyzer && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && rustup component add rustfmt rust-analyzer rust-src
# set -Ux EDITOR helix

theme = "dracula_at_night"

[keys.normal]
space.g = ":sh kitty -e lazygit"
