# NEED TO INSTALL
# sudo pacman -S git base-devel rustup helix rust-analyzer fd ripgrep && rustup component add rustfmt rust-src
# set -Ux EDITOR helix

theme = "dracula_at_night"

[keys.normal]
space.g = ":sh kitty -e lazygit"
